plugins {
    id 'com.android.application' version '8.2.0'
}

android {
    namespace 'app.studyclock'
    compileSdk 35

    defaultConfig {
        applicationId "app.studyclock"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    packagingOptions {
        exclude 'META-INF/proguard/androidx-*.pro'
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.9.24')
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
